runtime: python312

entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

handlers:
  # Static files handler
  - url: /static
    static_dir: static

  # Catch all handler directing to the main application
  - url: /.*
    script: auto
